name: pri_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sensors_plus: ^6.1.1
  camera: ^0.10.5
  cupertino_icons: ^1.0.8
  device_info_plus: ^9.1.2
  flutter_webrtc: ^0.12.0  # Updated to a more recent stable version
  socket_io_client: ^2.0.2  # Updated to latest stable version
  web_socket_channel: ^3.0.3
  network_info_plus: ^6.1.4
  connectivity_plus: ^6.1.4
  http: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
